DROP DATABASE IF EXISTS papyrus;
CREATE DATABASE papyrus;
USE papyrus;
CREATE TABLE PRODUIT(
CODART CHAR(4) NOT NULL,
LIBART VARCHAR(50) NOT NULL,
STKALE INT(10) NOT NULL,
STKPHY INT(10) NOT NULL,
QTEANN INT(10) NOT NULL,
UNIMES CHAR(5) NOT NULL,
PRIMARY KEY(CODART)
);
CREATE TABLE FOURNIS(
NUMFOU TINYINT NOT NULL,
NOMFOU VARCHAR(50) NOT NULL,
RUEFOU VARCHAR(50) NOT NULL,
POSFOU CHAR(5) NOT NULL,
VILFOU VARCHAR(30) NOT NULL,
CONFOU VARCHAR(50) NOT NULL,
SATISF TINYINT,
PRIMARY KEY(NUMFOU)
);
CREATE TABLE ENTCOM(
NUMCOM INT(10) NOT NULL,
OBSCOM VARCHAR(50),
DATCOM DATETIME(6),
NUMFOU TINYINT,
PRIMARY KEY(NUMCOM),
FOREIGN KEY(NUMFOU) REFERENCES FOURNIS(NUMFOU)
);
CREATE TABLE LIGCOM(
NUMCOM INT NOT NULL,
NUMLIG TINYINT NOT NULL,
CODART CHAR(4) NOT NULL,
QTECDE INT NOT NULL,
PRIUNI DECIMAL(9,2) NOT NULL,
QTELIV INT,
DERLIV DATETIME NOT NULL,
PRIMARY KEY(NUMLIG),
FOREIGN KEY(NUMCOM) REFERENCES ENTCOM(NUMCOM),
FOREIGN KEY(CODART) REFERENCES PRODUIT(CODART)
);
CREATE TABLE VENTE(
CODART CHAR(4) NOT NULL,
NUMFOU TINYINT NOT NULL,
DELLIV SMALLINT NOT NULL,
QTE1 INT NOT NULL,
PRIX1 DECIMAL(9,2) NOT NULL,
QTE2 INT,
PRIX2 DECIMAL(9,2),
QTE3 INT,
PRIX3 DECIMAL(9,2),
PRIMARY KEY(CODART,NUMFOU)
);


